language: python
python: "3.6"

script: python questions.py --overwrite --verbose

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: build
  on:
    branch: questions
  target-branch: gh-pages
  
