git:
  depth: false

language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

before_script:
  - '[ -e "./cc-test-reporter" ] || curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter && chmod +x ./cc-test-reporter && ./cc-test-reporter before-build'
after_script:
  - npm run codecov
  - ./cc-test-reporter after-build -t lcov -p ./coverage --exit-code $TRAVIS_TEST_RESULT --debug || echo 'Skipping cc-test-reporter after-build...'
  - cat ./coverage/lcov.info |  node_modules/.bin/codacy-coverage -f lcov
